# Introduction to Web Scraping

### Definition of Web Scraping:

Web Scraping is the automated process of extracting information from websites. This can include text, images, tables, and other data types.

### Why Scrape Data?:

- **Accessibility**: Many datasets are freely available online but not in a structured format. Scraping allows you to gather these datasets efficiently.
- **Real-time Data**: Scraping can provide real-time or frequently updated data, essential for market analysis or economic research.
- **Automation**: Automating data collection reduces time and human error.

### Ethical Considerations:

- **Legal Aspects**: Not all websites allow scraping. <span style="color:red"> It’s important to check a website’s `robots.txt` file, which provides guidelines for web crawlers.</span> Respect the website’s terms of service.
- **Ethical Practices**: Scrape responsibly—avoid making too many requests in a short period (rate limiting) to prevent overloading the website’s server.

### HTTP Status Codes:

When you request data from a webpage using Python, the server responds with an HTTP status code that indicates the result of the request. We want the HTTP Status to equal 200.

1.   List item
2.   List item



### <span style="color:red"> Why Check for Status Code 200? </span>
The status code 200 means the request was successful and the webpage is accessible. This is a good sign to proceed with scraping. If the status code is anything other than 200, it usually means there's an issue, and scraping should not proceed until the issue is resolved.

#### Common HTTP Status Codes:

- **200 (OK)**: The request was successful, and the server is returning the requested resource.
- **404 (Not Found)**: The requested resource could not be found on the server.
- **403 (Forbidden)**: The server understood the request but refuses to authorize it.
- **500 (Internal Server Error)**: The server encountered an unexpected condition that prevented it from fulfilling the request.

# 1. Libraries

- !pip install: This command installs the necessary Python libraries.
-requests is used to handle HTTP requests
- beautifulsoup4 (often abbreviated as bs4) is used to parse HTML and XML documents.

In [4]:
# Install necessary libraries
!pip install requests beautifulsoup4

# Importing libraries
import requests
from bs4 import BeautifulSoup

Requirement already satisfied: requests in /Users/andrealorensy/anaconda3/lib/python3.11/site-packages (2.32.3)
Requirement already satisfied: beautifulsoup4 in /Users/andrealorensy/anaconda3/lib/python3.11/site-packages (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/andrealorensy/anaconda3/lib/python3.11/site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/andrealorensy/anaconda3/lib/python3.11/site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/andrealorensy/anaconda3/lib/python3.11/site-packages (from requests) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/andrealorensy/anaconda3/lib/python3.11/site-packages (from requests) (2025.4.26)
Requirement already satisfied: soupsieve>1.2 in /Users/andrealorensy/anaconda3/lib/python3.11/site-packages (from beautifulsoup4) (2.4)

## 2. Checking Web Status

- requests.get(): This function sends an HTTP GET request to the specified URL. It returns a response object containing the server’s response to the request.

- response.status_code: This attribute of the response object holds the HTTP status code. Printing it helps us check if the request was successful (200) or if there was an issue.

- Conditional Check (if statement):
This checks if the status code is 200. If it is, we proceed with parsing the webpage’s content.
If the status code is not 200, it indicates an issue (like 404 or 500), and we print an error message instead.

In [7]:
# Sending a GET request to a sample website
#URL = 'https://www.cemfi.es/'
URL = 'https://crei.cat/'

response = requests.get(URL)

# Checking the status code of the response
print(f"Status Code: {response.status_code}")

# If the response is successful, proceed with parsing
if response.status_code == 200:
    print(f"Successfully accessed the webpage {URL}")
else:
    print(f"Failed to access the webpage: {URL}")

Status Code: 200
Successfully accessed the webpage https://crei.cat/

## 3. Getting the Raw Web Code

- response.content: This attribute of the response object contains the content of the response in bytes. It represents the raw HTML of the webpage we requested.

- BeautifulSoup(response.content, 'html.parser'): This line initializes a BeautifulSoup object using the HTML content from response.content and specifies the parser to use ('html.parser'). This parser converts the HTML into a BeautifulSoup object, which can be navigated and searched.

In [9]:
# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

print(soup)

<!DOCTYPE html>

<html lang="en-US">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<link href="https://gmpg.org/xfn/11" rel="profile"/>
<title>CREI – Centre de Recerca en Economia Internacional</title>
<link href="https://crei.cat/wp-content/themes/crei-theme/favicon.png" rel="icon" sizes="64x64" type="image/png"/>
<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-22729428-1', 'auto');
		ga('send', 'pageview');

	</script>
<meta content="max-image-preview:large" name="robots"/>
<style>img:is([sizes="auto" i], [sizes^="auto," i]) { contain-intrinsic-size: 3000px 1500px }</style>
<script type="text/javascript">
/* <![CDATA[ */
window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/15.1.0\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/15.1.0\/svg\/","svgExt":".svg","source":{"concatemoji":"https:\/\/crei.cat\/wp-includes\/js\/wp-emoji-release.min.js?ver=841920b67394c403ae3ed45dbd7d1b72"}};
/*! This file is auto-generated */
!function(i,n){var o,s,e;function c(e){try{var t={supportTests:e,timestamp:(new Date).valueOf()};sessionStorage.setItem(o,JSON.stringify(t))}catch(e){}}function p(e,t,n){e.clearRect(0,0,e.canvas.width,e.canvas.height),e.fillText(t,0,0);var t=new Uint32Array(e.getImageData(0,0,e.canvas.width,e.canvas.height).data),r=(e.clearRect(0,0,e.canvas.width,e.canvas.height),e.fillText(n,0,0),new Uint32Array(e.getImageData(0,0,e.canvas.width,e.canvas.height).data));return t.every(function(e,t){return e===r[t]})}function u(e,t,n){switch(t){case"flag":return n(e,"\ud83c\udff3\ufe0f\u200d\u26a7\ufe0f","\ud83c\udff3\ufe0f\u200b\u26a7\ufe0f")?!1:!n(e,"\ud83c\uddfa\ud83c\uddf3","\ud83c\uddfa\u200b\ud83c\uddf3")&&!n(e,"\ud83c\udff4\udb40\udc67\udb40\udc62\udb40\udc65\udb40\udc6e\udb40\udc67\udb40\udc7f","\ud83c\udff4\u200b\udb40\udc67\u200b\udb40\udc62\u200b\udb40\udc65\u200b\udb40\udc6e\u200b\udb40\udc67\u200b\udb40\udc7f");case"emoji":return!n(e,"\ud83d\udc26\u200d\ud83d\udd25","\ud83d\udc26\u200b\ud83d\udd25")}return!1}function f(e,t,n){var r="undefined"!=typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope?new OffscreenCanvas(300,150):i.createElement("canvas"),a=r.getContext("2d",{willReadFrequently:!0}),o=(a.textBaseline="top",a.font="600 32px Arial",{});return e.forEach(function(e){o[e]=t(a,e,n)}),o}function t(e){var t=i.createElement("script");t.src=e,t.defer=!0,i.head.appendChild(t)}"undefined"!=typeof Promise&&(o="wpEmojiSettingsSupports",s=["flag","emoji"],n.supports={everything:!0,everythingExceptFlag:!0},e=new Promise(function(e){i.addEventListener("DOMContentLoaded",e,{once:!0})}),new Promise(function(t){var n=function(){try{var e=JSON.parse(sessionStorage.getItem(o));if("object"==typeof e&&"number"==typeof e.timestamp&&(new Date).valueOf()<e.timestamp+604800&&"object"==typeof e.supportTests)return e.supportTests}catch(e){}return null}();if(!n){if("undefined"!=typeof Worker&&"undefined"!=typeof OffscreenCanvas&&"undefined"!=typeof URL&&URL.createObjectURL&&"undefined"!=typeof Blob)try{var e="postMessage("+f.toString()+"("+[JSON.stringify(s),u.toString(),p.toString()].join(",")+"));",r=new Blob([e],{type:"text/javascript"}),a=new Worker(URL.createObjectURL(r),{name:"wpTestEmojiSupports"});return void(a.onmessage=function(e){c(n=e.data),a.terminate(),t(n)})}catch(e){}c(n=f(s,u,p))}t(n)}).then(function(e){for(var t in e)n.supports[t]=e[t],n.supports.everything=n.supports.everything&&n.supports[t],"flag"!==t&&(n.supports.everythingExceptFlag=n.supports.everythingExceptFlag&&n.supports[t]);n.supports.everythingExceptFlag=n.supports.everythingExceptFlag&&!n.supports.flag,n.DOMReady=!1,n.readyCallback=function(){n.DOMReady=!0}}).then(function(){return e}).then(function(){var e;n.supports.everything||(n.readyCallback(),(e=n.source||{}).concatemoji?t(e.concatemoji):e.wpemoji&&e.twemoji&&(t(e.twemoji),t(e.wpemoji)))}))}((window,document),window._wpemojiSettings);
/* ]]> */
</script>
<style id="wp-emoji-styles-inline-css" type="text/css">

	img.wp-smiley, img.emoji {
		display: inline !important;
		border: none !important;
		box-shadow: none !important;
		height: 1em !important;
		width: 1em !important;
		margin: 0 0.07em !important;
		vertical-align: -0.1em !important;
		background: none !important;
		padding: 0 !important;
	}
</style>
<link href="https://crei.cat/wp-includes/css/dist/block-library/style.min.css?ver=841920b67394c403ae3ed45dbd7d1b72" id="wp-block-library-css" media="all" rel="stylesheet" type="text/css">
<style id="classic-theme-styles-inline-css" type="text/css">
/*! This file is auto-generated */
.wp-block-button__link{color:#fff;background-color:#32373c;border-radius:9999px;box-shadow:none;text-decoration:none;padding:calc(.667em + 2px) calc(1.333em + 2px);font-size:1.125em}.wp-block-file__button{background:#32373c;color:#fff;text-decoration:none}
</style>
<style id="global-styles-inline-css" type="text/css">
:root{--wp--preset--aspect-ratio--square: 1;--wp--preset--aspect-ratio--4-3: 4/3;--wp--preset--aspect-ratio--3-4: 3/4;--wp--preset--aspect-ratio--3-2: 3/2;--wp--preset--aspect-ratio--2-3: 2/3;--wp--preset--aspect-ratio--16-9: 16/9;--wp--preset--aspect-ratio--9-16: 9/16;--wp--preset--color--black: #000000;--wp--preset--color--cyan-bluish-gray: #abb8c3;--wp--preset--color--white: #ffffff;--wp--preset--color--pale-pink: #f78da7;--wp--preset--color--vivid-red: #cf2e2e;--wp--preset--color--luminous-vivid-orange: #ff6900;--wp--preset--color--luminous-vivid-amber: #fcb900;--wp--preset--color--light-green-cyan: #7bdcb5;--wp--preset--color--vivid-green-cyan: #00d084;--wp--preset--color--pale-cyan-blue: #8ed1fc;--wp--preset--color--vivid-cyan-blue: #0693e3;--wp--preset--color--vivid-purple: #9b51e0;--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple: linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%);--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan: linear-gradient(135deg,rgb(122,220,180) 0%,rgb(0,208,130) 100%);--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange: linear-gradient(135deg,rgba(252,185,0,1) 0%,rgba(255,105,0,1) 100%);--wp--preset--gradient--luminous-vivid-orange-to-vivid-red: linear-gradient(135deg,rgba(255,105,0,1) 0%,rgb(207,46,46) 100%);--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray: linear-gradient(135deg,rgb(238,238,238) 0%,rgb(169,184,195) 100%);--wp--preset--gradient--cool-to-warm-spectrum: linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%);--wp--preset--gradient--blush-light-purple: linear-gradient(135deg,rgb(255,206,236) 0%,rgb(152,150,240) 100%);--wp--preset--gradient--blush-bordeaux: linear-gradient(135deg,rgb(254,205,165) 0%,rgb(254,45,45) 50%,rgb(107,0,62) 100%);--wp--preset--gradient--luminous-dusk: linear-gradient(135deg,rgb(255,203,112) 0%,rgb(199,81,192) 50%,rgb(65,88,208) 100%);--wp--preset--gradient--pale-ocean: linear-gradient(135deg,rgb(255,245,203) 0%,rgb(182,227,212) 50%,rgb(51,167,181) 100%);--wp--preset--gradient--electric-grass: linear-gradient(135deg,rgb(202,248,128) 0%,rgb(113,206,126) 100%);--wp--preset--gradient--midnight: linear-gradient(135deg,rgb(2,3,129) 0%,rgb(40,116,252) 100%);--wp--preset--font-size--small: 13px;--wp--preset--font-size--medium: 20px;--wp--preset--font-size--large: 36px;--wp--preset--font-size--x-large: 42px;--wp--preset--spacing--20: 0.44rem;--wp--preset--spacing--30: 0.67rem;--wp--preset--spacing--40: 1rem;--wp--preset--spacing--50: 1.5rem;--wp--preset--spacing--60: 2.25rem;--wp--preset--spacing--70: 3.38rem;--wp--preset--spacing--80: 5.06rem;--wp--preset--shadow--natural: 6px 6px 9px rgba(0, 0, 0, 0.2);--wp--preset--shadow--deep: 12px 12px 50px rgba(0, 0, 0, 0.4);--wp--preset--shadow--sharp: 6px 6px 0px rgba(0, 0, 0, 0.2);--wp--preset--shadow--outlined: 6px 6px 0px -3px rgba(255, 255, 255, 1), 6px 6px rgba(0, 0, 0, 1);--wp--preset--shadow--crisp: 6px 6px 0px rgba(0, 0, 0, 1);}:where(.is-layout-flex){gap: 0.5em;}:where(.is-layout-grid){gap: 0.5em;}body .is-layout-flex{display: flex;}.is-layout-flex{flex-wrap: wrap;align-items: center;}.is-layout-flex > :is(*, div){margin: 0;}body .is-layout-grid{display: grid;}.is-layout-grid > :is(*, div){margin: 0;}:where(.wp-block-columns.is-layout-flex){gap: 2em;}:where(.wp-block-columns.is-layout-grid){gap: 2em;}:where(.wp-block-post-template.is-layout-flex){gap: 1.25em;}:where(.wp-block-post-template.is-layout-grid){gap: 1.25em;}.has-black-color{color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-color{color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-color{color: var(--wp--preset--color--white) !important;}.has-pale-pink-color{color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-color{color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-color{color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-color{color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-color{color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-color{color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-color{color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-color{color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-color{color: var(--wp--preset--color--vivid-purple) !important;}.has-black-background-color{background-color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-background-color{background-color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-background-color{background-color: var(--wp--preset--color--white) !important;}.has-pale-pink-background-color{background-color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-background-color{background-color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-background-color{background-color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-background-color{background-color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-background-color{background-color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-background-color{background-color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-background-color{background-color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-background-color{background-color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-background-color{background-color: var(--wp--preset--color--vivid-purple) !important;}.has-black-border-color{border-color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-border-color{border-color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-border-color{border-color: var(--wp--preset--color--white) !important;}.has-pale-pink-border-color{border-color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-border-color{border-color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-border-color{border-color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-border-color{border-color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-border-color{border-color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-border-color{border-color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-border-color{border-color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-border-color{border-color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-border-color{border-color: var(--wp--preset--color--vivid-purple) !important;}.has-vivid-cyan-blue-to-vivid-purple-gradient-background{background: var(--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple) !important;}.has-light-green-cyan-to-vivid-green-cyan-gradient-background{background: var(--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan) !important;}.has-luminous-vivid-amber-to-luminous-vivid-orange-gradient-background{background: var(--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange) !important;}.has-luminous-vivid-orange-to-vivid-red-gradient-background{background: var(--wp--preset--gradient--luminous-vivid-orange-to-vivid-red) !important;}.has-very-light-gray-to-cyan-bluish-gray-gradient-background{background: var(--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray) !important;}.has-cool-to-warm-spectrum-gradient-background{background: var(--wp--preset--gradient--cool-to-warm-spectrum) !important;}.has-blush-light-purple-gradient-background{background: var(--wp--preset--gradient--blush-light-purple) !important;}.has-blush-bordeaux-gradient-background{background: var(--wp--preset--gradient--blush-bordeaux) !important;}.has-luminous-dusk-gradient-background{background: var(--wp--preset--gradient--luminous-dusk) !important;}.has-pale-ocean-gradient-background{background: var(--wp--preset--gradient--pale-ocean) !important;}.has-electric-grass-gradient-background{background: var(--wp--preset--gradient--electric-grass) !important;}.has-midnight-gradient-background{background: var(--wp--preset--gradient--midnight) !important;}.has-small-font-size{font-size: var(--wp--preset--font-size--small) !important;}.has-medium-font-size{font-size: var(--wp--preset--font-size--medium) !important;}.has-large-font-size{font-size: var(--wp--preset--font-size--large) !important;}.has-x-large-font-size{font-size: var(--wp--preset--font-size--x-large) !important;}
:where(.wp-block-post-template.is-layout-flex){gap: 1.25em;}:where(.wp-block-post-template.is-layout-grid){gap: 1.25em;}
:where(.wp-block-columns.is-layout-flex){gap: 2em;}:where(.wp-block-columns.is-layout-grid){gap: 2em;}
:root :where(.wp-block-pullquote){font-size: 1.5em;line-height: 1.6;}
</style>
<link href="https://crei.cat/wp-content/plugins/cookie-law-info/legacy/public/css/cookie-law-info-public.css?ver=3.2.10" id="cookie-law-info-css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://crei.cat/wp-content/plugins/cookie-law-info/legacy/public/css/cookie-law-info-gdpr.css?ver=3.2.10" id="cookie-law-info-gdpr-css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://crei.cat/wp-content/themes/crei-theme/assets/css/styles.css" id="mg-style-css" media="all" rel="stylesheet" type="text/css"/>
<style id="akismet-widget-style-inline-css" type="text/css">

			.a-stats {
				--akismet-color-mid-green: #357b49;
				--akismet-color-white: #fff;
				--akismet-color-light-grey: #f6f7f7;

				max-width: 350px;
				width: auto;
			}

			.a-stats * {
				all: unset;
				box-sizing: border-box;
			}

			.a-stats strong {
				font-weight: 600;
			}

			.a-stats a.a-stats__link,
			.a-stats a.a-stats__link:visited,
			.a-stats a.a-stats__link:active {
				background: var(--akismet-color-mid-green);
				border: none;
				box-shadow: none;
				border-radius: 8px;
				color: var(--akismet-color-white);
				cursor: pointer;
				display: block;
				font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen-Sans', 'Ubuntu', 'Cantarell', 'Helvetica Neue', sans-serif;
				font-weight: 500;
				padding: 12px;
				text-align: center;
				text-decoration: none;
				transition: all 0.2s ease;
			}

			/* Extra specificity to deal with TwentyTwentyOne focus style */
			.widget .a-stats a.a-stats__link:focus {
				background: var(--akismet-color-mid-green);
				color: var(--akismet-color-white);
				text-decoration: none;
			}

			.a-stats a.a-stats__link:hover {
				filter: brightness(110%);
				box-shadow: 0 4px 12px rgba(0, 0, 0, 0.06), 0 0 2px rgba(0, 0, 0, 0.16);
			}

			.a-stats .count {
				color: var(--akismet-color-white);
				display: block;
				font-size: 1.5em;
				line-height: 1.4;
				padding: 0 13px;
				white-space: nowrap;
			}

</style>
<script id="jquery-core-js" src="https://crei.cat/wp-includes/js/jquery/jquery.min.js?ver=3.7.1" type="text/javascript"></script>
<script id="jquery-migrate-js" src="https://crei.cat/wp-includes/js/jquery/jquery-migrate.min.js?ver=3.4.1" type="text/javascript"></script>
<script id="cookie-law-info-js-extra" type="text/javascript">
/* <![CDATA[ */
var Cli_Data = {"nn_cookie_ids":["test_cookie","li_sugr","bcookie","bscookie","_ga","_gid","_hjFirstSeen","_hjSessionUser_*","_hjSession_*","AnalyticsSyncHistory","lidc","_hjAbsoluteSessionInProgress","UserMatchHistory","li_gc","_gat","AWSALB","dbpb5zDmgTrLAA1Q6g@@","_hjIncludedInSessionSample_3062403","CookieLawInfoConsent","cookielawinfo-checkbox-necessary","cookielawinfo-checkbox-non-necessary","cookielawinfo-checkbox-functional","cookielawinfo-checkbox-performance","cookielawinfo-checkbox-analytics","cookielawinfo-checkbox-advertisement","cookielawinfo-checkbox-others","AWSALBCORS"],"cookielist":[],"non_necessary_cookies":{"necessary":["CookieLawInfoConsent","AWSALBCORS"],"functional":["lidc","_hjAbsoluteSessionInProgress","UserMatchHistory","li_gc"],"performance":["_gat","AWSALB"],"analytics":["_ga","_gid","_hjFirstSeen","_hjSessionUser_*","_hjSession_*","AnalyticsSyncHistory"],"advertisement":["test_cookie","li_sugr","bcookie","bscookie"],"others":["dbpb5zDmgTrLAA1Q6g@@","_hjIncludedInSessionSample_3062403"]},"ccpaEnabled":"","ccpaRegionBased":"","ccpaBarEnabled":"","strictlyEnabled":["necessary","obligatoire"],"ccpaType":"gdpr","js_blocking":"1","custom_integration":"","triggerDomRefresh":"","secure_cookies":""};
var cli_cookiebar_settings = {"animate_speed_hide":"500","animate_speed_show":"500","background":"#FFF","border":"#b1a6a6c2","border_on":"","button_1_button_colour":"#61a229","button_1_button_hover":"#4e8221","button_1_link_colour":"#fff","button_1_as_button":"1","button_1_new_win":"","button_2_button_colour":"#333","button_2_button_hover":"#292929","button_2_link_colour":"#444","button_2_as_button":"","button_2_hidebar":"","button_3_button_colour":"#3566bb","button_3_button_hover":"#2a5296","button_3_link_colour":"#fff","button_3_as_button":"1","button_3_new_win":"","button_4_button_colour":"#000","button_4_button_hover":"#000000","button_4_link_colour":"#333333","button_4_as_button":"","button_7_button_colour":"#61a229","button_7_button_hover":"#4e8221","button_7_link_colour":"#fff","button_7_as_button":"1","button_7_new_win":"","font_family":"inherit","header_fix":"","notify_animate_hide":"1","notify_animate_show":"","notify_div_id":"#cookie-law-info-bar","notify_position_horizontal":"right","notify_position_vertical":"bottom","scroll_close":"","scroll_close_reload":"","accept_close_reload":"","reject_close_reload":"","showagain_tab":"1","showagain_background":"#fff","showagain_border":"#000","showagain_div_id":"#cookie-law-info-again","showagain_x_position":"100px","text":"#333333","show_once_yn":"","show_once":"10000","logging_on":"","as_popup":"","popup_overlay":"1","bar_heading_text":"","cookie_bar_as":"banner","popup_showagain_position":"bottom-right","widget_position":"left"};
var log_object = {"ajax_url":"https:\/\/crei.cat\/wp-admin\/admin-ajax.php"};
/* ]]> */
</script>
<script id="cookie-law-info-js" src="https://crei.cat/wp-content/plugins/cookie-law-info/legacy/public/js/cookie-law-info-public.js?ver=3.2.10" type="text/javascript"></script>
<script id="mg-scripts-js" src="https://crei.cat/wp-content/themes/crei-theme/assets/js/all.min.js" type="text/javascript"></script>

## 4. Extracting data from Raw Code Patterns

- First a Mickey Mouse example to extract links from a webpage

In [11]:
# Example: Extracting all the hyperlinks on the page
links = soup.find_all('a')

# Print all the hyperlinks
for link in links:
    print(link.get('href'))

/
/
https://crei.cat/about-crei/
https://crei.cat/people/
https://crei.cat/people#researchers
https://crei.cat/people#a-researchers
https://crei.cat/people#v-researchers
https://crei.cat/people#fv-researchers
https://crei.cat/people#staff
https://crei.cat/working-papers/
https://crei.cat/opuscles/
https://crei.cat/activities/
https://crei.cat/seminars/
https://crei.cat/conferences/
https://crei.cat/crei-lectures-in-macroeconomics/
https://crei.cat/bojos-per-leconomia/
https://crei.cat/barcelona-crei-macroeconomics-summer-school/
https://crei.cat/news/
https://crei.cat/news-at-crei/
https://crei.cat/crei-in-the-news/
https://crei.cat/work-with-us/
https://crei.cat/contact/
https://crei.cat/links/
https://twitter.com/CREIResearch
https://www.linkedin.com/company/centre-de-recerca-en-economia-internacional
https://crei.cat/people/fornaro/
https://crei.cat/people/ponzetto/
https://crei.cat/people/broner/
https://crei.cat/people/martin/
https://crei.cat/people/ramon-marimon/
https://crei.cat/people/fornaro/
https://crei.cat/people/hugo-reichardt-2/
https://crei.cat/people/gali/
https://crei.cat/people/davide-debortoli-2/
https://crei.cat/people/nagy/
https://crei.cat/people/asriyan/
https://crei.cat/people/martin/
https://crei.cat/people/victoria-vanasco-2/
https://crei.cat/people/isaac-baley/
https://crei.cat/publications/
https://macromusings.libsyn.com/luca-fornaro-on-hysteresis-endogenous-growth-and-aggregate-demand-polices
https://www.youtube.com/watch?v=-aeerzmpGUg
https://www.3cat.cat/3cat/jordi-gali-trump-vol-els-aranzels-per-obtenir-guanys-en-camps-que-no-son-el-comerc-internacional/audio/1240360/
https://www.rac1.cat/economia/20250405/248470/jordi-gali-economista-sobre-impacte-aranzels-trump-europa-escalada-podria-portar-desastre-absolut-vialliure.html
https://crei.cat/news-at-crei/
https://crei.cat/recruitment-seminars/
https://crei.cat/wp-content/uploads/2024/10/CREI-Recruitment-Ad.pdf
https://crei.cat/bojos-per-leconomia/
https://crei.cat/barcelona-crei-macroeconomics-summer-school/
https://crei.cat/conferences/
https://crei.cat/conferences/
https://crei.cat/conferences/
https://crei.cat/event-list/
https://www.upf.edu/en/
http://web.gencat.cat/ca/inici/
https://cerca.cat/
https://www.upf.edu/web/econ/home
https://bse.eu
https://crei.cat/about-crei/
https://crei.cat/people/
https://crei.cat/opuscles/
https://crei.cat/terms-conditions/
https://crei.cat/privacy-notice/
https://crei.cat/cookies-policy/
https://crei.cat/accessibility/
https://crei.cat/transparency-portal/
/hr-excellence/
None
None
None
None
None
None
None
None
None
None
None
https://www.cookieyes.com/

### Next, scrape the sections of the CEMFI webpage.

In [13]:
import requests
from bs4 import BeautifulSoup

# Step 1: Send a GET request to the webpage
url = "https://www.cemfi.es/"
response = requests.get(url)

# Step 2: Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

print(soup.find_all())

[<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
<!--[if IE 8]> <html lang="es" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="es" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="es">
<!--<![endif]--><head>
<meta content="text/html;charset=utf-8" http-equiv="Content-Type"/>
<meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"/>
<meta content="CEMFI | Institución creada por el Banco de España para la formación de postgrado y la investigación en el ámbito de la economía." name="description"/>
<meta content="Cemfi" name="author"/>
<title>CEMFI</title>
<link href="https://cemfi.es" rel="canonical"/>
<link href="/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="/favicon.ico" rel="icon" type="image/x-icon"/>
<!-- Bootstrap core CSS -->
<link href="/assets/css/bootstrap.min.css" rel="stylesheet"/>
<link href="/assets/css/all.min.css" rel="stylesheet"/> <!-- FontAwesome -->
<!-- Estilos componentenes -->
<link href="/assets/css/owlcarousel/owl.carousel.min.css" rel="stylesheet"/>
<link href="/assets/css/owlcarousel/owl.theme.default.min.css" rel="stylesheet"/>
<!-- Estilos componentenes -->
<link href="/assets/css/owlcarousel/owl.carousel.min.css" rel="stylesheet"/>
<link href="/assets/css/owlcarousel/owl.theme.default.min.css" rel="stylesheet"/>
<link href="/assets/css/bootstrap-select/bootstrap-select.min.css" rel="stylesheet"/>
<link href="/assets/css/datepicker/gijgo.min.css" rel="stylesheet"/>
<link href="/assets/css/datepicker/leadin.css" rel="stylesheet"/>
<!-- Estilos Tema-->
<link href="/assets/css/cemfi.css" rel="stylesheet"/>
<link href="/assets/css/leadin.css" rel="stylesheet"/>
<link href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,500;0,700;1,400&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&amp;family=Ubuntu:ital,wght@0,700;1,400;1,500&amp;display=swap" rel="stylesheet"/>
</head>
<!-- Google analytics -->
<!-- Global site tag (gtag.js) - Google Analytics --> <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-4756095-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-4756095-2');
</script>
<!-- Google analytics -->
<!-- Cookies Mensaje De Alerta -->
<script language="JavaScript">

function muestra_oculta(id){
 if (document.getElementById){ //se obtiene el id
 var el = document.getElementById(id); //se define la variable "el" igual a nuestro div
 el.style.display = (el.style.display == 'none') ? 'block' : 'none'; //damos un atributo display:none que oculta el div
 }
}

function acept_cookie() {
	var a = new Date();
	a = new Date(a.getTime() +2000*60*60*24*365);
	document.cookie = "cookieextreme=YY; expires=" + a.toGMTString() + ";";
}

function conf_cookie() {
	// window.location.href("cookie_configuration.asp");
	window.location.href='cookies.asp';
	return false;
}

</script>
<div class="alert text-center cookiealert" role="alert" style="opacity: 70%; font-size: 15px;">
<b>We use first and third party cookies to ensure the operation of the site and analyze traffic on our website. More information in our <a href="/cookies.asp">Cookie Policy</a></b>. <a class="btn btn-primary btn-sm" href="/cookies.asp" style="text-decoration: none;" target="_blank">Configure and reject cookies</a>
<button class="btn btn-primary btn-sm acceptcookies" type="button">
<a href="javascript:acept_cookie()" style="color: white; text-decoration: none;">Accept all cookies</a>
</button>
</div>
<!-- Variables internat de Control -->
<body>
<header>
<nav class="navbar navbar-expand-lg navbar-white fixed-top bg-white">
<div class="container">
<a class="navbar-brand" href="/index.asp"><img alt="Cemfi Logo" src="/images/Logo-Azul.png" title="Cemfi Logo"/></a>
<button aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" class="custom-toggler navbar-toggler" data-target="#navbarCollapse" data-toggle="collapse" type="button">
<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarCollapse">
<ul class="navbar-nav mx-auto" id="cemfi-menu-top">
<li class="nav-item active dropdown"><a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="/research/index.asp" id="dropdown-personas" role="button">Research</a>
<div aria-labelledby="dropdown-personas" class="dropdown-menu">
<a aria-expanded="false" aria-haspopup="true" class="dropdown-ite nav-link dropdown-toggle has-dropdown" data-toggle="dropdown" href="/research/research_lines/index.asp" id="dropdown-personas" role="button">Research lines</a>
<div class="dropdown-menu researchlinesMenu">
<a class="dropdown-item" href="/research/research_lines/research_line.asp?q=macroeconomics">Macroeconomics</a>
<a class="dropdown-item" href="/research/research_lines/research_line.asp?q=microeconomics">Microeconomics</a>
<a class="dropdown-item" href="/research/research_lines/research_line.asp?q=applied">Applied Economics</a>
<a class="dropdown-item" href="/research/research_lines/research_line.asp?q=banking">Banking and Finance</a>
<a class="dropdown-item" href="/research/research_lines/research_line.asp?q=econometrics">Econometrics</a>
</div>
<a class="dropdown-item" href="/research/seminars/index.asp">Seminars</a>
<a class="dropdown-item" href="/research/projects/index.asp">Research grants</a>
<a class="dropdown-item" href="/research/mdm/index.asp">MdM Unit of Excellence</a>
<a class="dropdown-item" href="/research/conferences/index.asp">Research conferences</a>
<a class="dropdown-item" href="/research/collaborations/index.asp">Collaborations</a>
<a class="dropdown-item" href="/research/pub/index.asp">Publications</a>
<a class="dropdown-item" href="/research/publications/index.asp">Working Papers</a>
</div>
</li>
<li class="nav-item active dropdown"><a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="/programs/index.asp" id="dropdown-personas" role="button">Programs</a>
<div aria-labelledby="dropdown-personas" class="dropdown-menu">
<a class="dropdown-item" href="/programs/master/index.asp">Master in Economics and Finance</a>
<a class="dropdown-item" href="/programs/phd/index.asp">PhD in Economics</a>
<a class="dropdown-item" href="/programs/internship/index.asp">Undergraduate Internships</a>
<a class="dropdown-item" href="/programs/css/index.asp">CEMFI Summer School</a>
<a class="dropdown-item" href="/programs/dsb/index.asp">Diploma in Banking Supervision</a>
</div>
</li>
<li class="nav-item active dropdown"><a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="/people/index.asp" id="dropdown-personas" role="button">People</a>
<div aria-labelledby="dropdown-personas" class="dropdown-menu">
<a class="dropdown-item" href="/people/faculty/index.asp">Academic staff</a>
<a class="dropdown-item" href="/people/faculty/index_ext.asp">External faculty</a>
<a class="dropdown-item" href="/people/visitors/index.asp">Visitors</a>
<a class="dropdown-item" href="/people/research/index.asp">Research Fellows</a>
<a class="dropdown-item" href="/people/faculty/index_PhD.asp">PhD students</a>
<a class="dropdown-item" href="/people/staff/index.asp">Administrative staff</a>
</div>
</li>
<li class="nav-item active dropdown"><a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="/about/index.asp" id="dropdown-personas" role="button">About</a>
<div aria-labelledby="dropdown-personas" class="dropdown-menu">
<a class="dropdown-item" href="/about/whoweare/index.asp">Welcome to CEMFI</a>
<a class="dropdown-item" href="/about/management/index.asp">Governing bodies</a>
<a class="dropdown-item" href="/about/bde/index.asp">CEMFI and Banco de España</a>
<a class="dropdown-item" href="/about/transparency/index.asp">Transparency</a>
<a class="dropdown-item" href="/about/ethics/index.asp">Ethics</a>
<a class="dropdown-item" href="/about/resources/index.asp">Human Resources Excellence</a>
<a class="dropdown-item" href="/about/location/index.asp">Location</a>
</div>
</li>
</ul>
<ul class="navbar-nav ml-auto">
<li class="nav-item d-flex">
<div class="" id="searchForm" style="padding-top: 10px;">
<form action="/google.asp" id="cse-search-box" name="cse-search-box">
<input name="cx" type="hidden" value="012421213609435000883:uswwidpw_jw"/>
<input id="cof" name="hidden" type="hidden" value="FORID:11"/>
<label class="label_bus" for="q"><span style="font-size: 0px;">.</span></label>
<div class="input-group mb-3">
<input class="form-control border-1 bg-light" id="q" name="q" onfocus="clearText(this)" size="25" type="text" value=""/>
<div class="input-group-append">
<span class="input-group-text" id="basic-addon2"><img alt="Search" src="/assets/img/icon-search.png" width="15"/></span>
</div>
</div>
</form>
</div>
</li>
</ul><div class="dropdown">
<a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="lang-select">ENG</a>
<div aria-labelledby="lang-select" class="dropdown-menu" style="height: 40px;">
<a href="/language.asp">ESP</a>
</div>
</div>
</div>
</div>
</nav>
</header>
<main role="main">
<!-- Carousel Portada-->
<div class="carousel slide" data-ride="carousel" id="carousel-portada">
<!-- Indicadores -->
<ol class="carousel-indicators">
<li class="active" data-slide-to="0" data-target="#carousel-portada"></li>
<li data-slide-to="1" data-target="#carousel-portada"></li>
<li data-slide-to="2" data-target="#carousel-portada"></li>
</ol>
<!-- End Indicadores -->
<div class="carousel-inner">
<div class="carousel-item active">
<img src="/images/portada/CSS-Dream.jpg"/>
<div class="carousel-caption container text-left">
<p class="carousel-title"><span style="color: #223b8b; font-size: 35px;">Applications to the CEMFI Summer School are open</span></p>
<div class="botones">
<a class="btn btn-lg btn-primary" href="/programs/css/courses.asp" role="button">Courses</a>
<a class="btn btn-lg btn-primary" href="/forms-cemfi/css/apply.asp" role="button">Apply Now</a>
</div>
</div>
</div>
<div class="carousel-item">
<img src="/images/portada/Natalia-Fabra-BANNER.jpg"/>
<div class="carousel-caption container text-left">
<p class="carousel-title"><span style="color: #223b8b; font-size: 35px;">We are very pleased to welcome Natalia Fabra as a full professor at CEMFI, effective June 1, 2025</span></p>
<div class="botones">
<a alt="Information about " class="btn btn-lg btn-primary" href="all_news_blog_detail.asp?id=530" role="button" title="Information about ">See more</a>
</div>
</div>
</div>
<div class="carousel-item">
<img src="/images/portada/Banner-Hiring-3.jpg"/>
<div class="carousel-caption container text-left">
<p class="carousel-title"><span style="color: #223b8b; font-size: 35px;">Job Market Placements of the Year 2025 Announced</span></p>
<div class="botones">
<a alt="Information about " class="btn btn-lg btn-primary" href="all_news_blog_detail.asp?id=526" role="button" title="Information about ">See more</a>
</div>
</div>
</div>
</div>
</div>
<!-- End Carousel Portada-->
<!-- Bloque Estudia en CEMFI -->
<section id="blq-estudia-cemfi">
<div class="container">
<!-- Row 1-->
<div class="row">
<div class="col-lg-4">
<div class="p-4 no-bg">
<h2>Excellence in Research and Teaching</h2>
<p>
              	CEMFI is a leading graduate school in Economics in the heart of Madrid.
              </p>
</div>
</div>
<div class="white-box col-lg-4">
<div class="p-4">
<h2>Master in Economics and Finance</h2>
<p>
              	A rigorous two-year program that successfully places students in the professional job market as well as in top doctoral programs.
              </p>
<a class="link-primary" href="/programs/master/index.asp">See more</a>
</div>
</div>
<div class="white-box col-lg-4">
<div class="p-4">
<h2>PhD in<br/>Economics</h2>
<p>
              	A selective doctoral program that is endorsed by the quality of its placements and the career paths of its graduates.
              </p>
<a class="link-primary" href="/programs/phd/index.asp">See more</a>
</div>
</div>
</div> <!-- End Row-->
<!-- Row 2-->
<div class="row">
<div class="white-box col-lg-4">
<div class="p-4">
<h2>Undergraduate Summer Internships</h2>
<p>
              	An opportunity to gain valuable work experience in economic research and data analysis.
              </p>
<a class="link-primary" href="/programs/internship/index.asp">See more</a>
</div>
</div>
<div class="white-box col-lg-4">
<div class="p-4">
<h2>Research</h2>
<p>
              	Our faculty are leaders in their fields of expertise and regularly publish in the leading journals of Economics.
              </p>
<a class="link-primary" href="/research/pub/index.asp">See more</a>
</div>
</div>
<div class="white-box col-lg-4">
<div class="p-4">
<h2>Summer<br/>School</h2>
<p>
              	Intensive, one-week courses covering the most recent developments in fields within CEMFI's range of expertise.
              </p>
<a class="link-primary" href="/programs/css/index.asp">See more</a>
</div>
</div>
</div> <!-- End Row 2-->
</div> <!-- End Container-->
</section><!-- End Bloque Bloque Estudia en CEMFI -->
<!-- Bloque Carusel Eventos -->
<section id="blq-carousel-eventos">
<div class="container">
<div class="row">
<div class="col-6">
<h2>Events</h2>
</div>
<div class="col-6 text-right">
<a class="link-primary link-square" href="/research/seminars/index.asp">See all seminars</a>
</div>
</div>
<!--Carousel Wrapper-->
<div class="container p-0">
<div class="owl-carousel">
<!-- Event Item -->
<div class="event mb-2">
<div class="event-header">
<div class="date"><span class="day">16</span><br/><span class="month"> JUN </span></div>
<div class="time">13:30h</div>
</div>
<div class="event-body">
<h4 class="event-title">Banking and Finance Seminar</h4>
<p class="event-text">joint FIRMS - Natalia Fabra (CEMFI) presents "The Costs of Counterparty Risk in Long-Term Contracts"
							(joint with Gerard Llobet)
						</p>
</div>
</div>
<div class="event mb-2">
<div class="event-header">
<div class="date"><span class="day">16</span><br/><span class="month"> JUN </span></div>
<div class="time">13:30h</div>
</div>
<div class="event-body">
<h4 class="event-title">FIRMS Seminar</h4>
<p class="event-text">joint Banking and Finance - Natalia Fabra (CEMFI) presents "The Costs of Counterparty Risk in Long-Term Contracts"
							(joint with Gerard Llobet)
						</p>
</div>
</div>
<div class="event mb-2">
<div class="event-header">
<div class="date"><span class="day">17</span><br/><span class="month"> JUN </span></div>
<div class="time">13:00h</div>
</div>
<div class="event-body">
<h4 class="event-title">FIRMS Seminar</h4>
<p class="event-text">joint Econometrics Seminar - Eugenio Miravete (The University of Texas at Austin) presents <a class="link-primary" href="../../ftp/pdf/papers/wshop/MST_Curvature.pdf" target="blank" title="PDF File. Opens in a new window">"Elasticity and Curvature of Discrete Choice Demand Models"</a>
							(joint with Katja Seim and Jeff Thurk)
						</p>
</div>
</div>
<div class="event mb-2">
<div class="event-header">
<div class="date"><span class="day">17</span><br/><span class="month"> JUN </span></div>
<div class="time">13:30h</div>
</div>
<div class="event-body">
<h4 class="event-title">Econometrics Seminar</h4>
<p class="event-text">joint FIRMS - Eugenio Miravete (The University of Texas at Austin) presents <a class="link-primary" href="../../ftp/pdf/papers/Seminar/MST_Curvature.pdf" target="blank" title="PDF File. Opens in a new window">"Elasticity and Curvature of Discrete Choice Demand Models"</a>
							(joint with Katja Seim and Jeff Thurk)
						</p>
</div>
</div>
<div class="event mb-2">
<div class="event-header">
<div class="date"><span class="day">19</span><br/><span class="month"> JUN </span></div>
<div class="time">13:30h</div>
</div>
<div class="event-body">
<h4 class="event-title">Applied Microeconomics Seminar (AMiS)</h4>
<p class="event-text">Luis Armona (Harvard Kennedy School) presents "TBA"</p>
</div>
</div>
<!-- End Event Item -->
<!-- End Event Item -->
</div> <!-- End Owl-->
</div> <!-- End Container-->
</div></section><!-- End Bloque Carousel Eventos-->
<!-- Bloque Noticias -->
<section id="blq-news">
<div class="container">
<div class="row py-3">
<div class="col-6">
<h2>News</h2>
</div>
<div class="col-6 text-right">
<a class="link-primary link-square" href="all_news_blog.asp">See all news</a>
</div>
</div>
<div class="news-wrapper">
<div class="row p-0 my-3">
</div>
<div class="row p-0 my-3">
<div class="col-md-6 col-sm-6 p-4">
<div class="row news-item">
<div class="col-lg-6 col-md-12 p-0">
<img alt="Olympia Bover has been awarded with Premio Womenvalue in Economics 2025" class="img-fluid" src="/images/news/OB-Cuadrada.jpg" title="Olympia Bover has been awarded with Premio Womenvalue in Economics 2025" width="300"/>
</div>
<div class="col-lg-6 col-md-12 bg-white p-4">
<h3><a href="all_news_blog_detail.asp?id=531">Olympia Bover has been awarded with Premio Womenvalue in Economics 2025</a></h3>
<a class="link-primary" href="all_news_blog_detail.asp?id=531">See more</a>
</div>
</div>
</div>
<div class="col-md-6 col-sm-6 p-4">
<div class="row news-item">
<div class="col-lg-6 col-md-12 p-0">
<img alt="We are very pleased to welcome Natalia Fabra as a full professor at CEMFI, effective June 1, 2025" class="img-fluid" src="/images/news/Natalia-Fabra-CUADRADA.jpg" title="We are very pleased to welcome Natalia Fabra as a full professor at CEMFI, effective June 1, 2025" width="300"/>
</div>
<div class="col-lg-6 col-md-12 bg-white p-4">
<h3><a href="all_news_blog_detail.asp?id=530">We are very pleased to welcome Natalia Fabra as a full professor at CEMFI, effective June 1, 2025</a></h3>
<a class="link-primary" href="all_news_blog_detail.asp?id=530">See more</a>
</div>
</div>
</div>
<div class="col-md-6 col-sm-6 p-4">
<div class="row news-item">
<div class="col-lg-6 col-md-12 p-0">
<img alt="Gilles Duranton (University of Pennsylvania) and Diego Puga (CEMFI) have received the 2025 Maurice Allais Economics Award" class="img-fluid" src="/images/news/Puga-Cuadrada_1.jpg" title="Gilles Duranton (University of Pennsylvania) and Diego Puga (CEMFI) have received the 2025 Maurice Allais Economics Award" width="300"/>
</div>
<div class="col-lg-6 col-md-12 bg-white p-4">
<h3><a href="all_news_blog_detail.asp?id=529">Gilles Duranton (University of Pennsylvania) and Diego Puga (CEMFI) have received the 2025 Maurice Allais Economics ...</a></h3>
<a class="link-primary" href="all_news_blog_detail.asp?id=529">See more</a>
</div>
</div>
</div>
<div class="col-md-6 col-sm-6 p-4">
<div class="row news-item">
<div class="col-lg-6 col-md-12 p-0">
<img alt="CEMFI endows 10 scholarships for its II School of Economics on Social Challenges: Aging, Gender, and Immigration at UIMP in Santander" class="img-fluid" src="/images/news/Cemfi-UIMP-Cuadrada_1.jpg" title="CEMFI endows 10 scholarships for its II School of Economics on Social Challenges: Aging, Gender, and Immigration at UIMP in Santander" width="300"/>
</div>
<div class="col-lg-6 col-md-12 bg-white p-4">
<h3><a href="all_news_blog_detail.asp?id=523">CEMFI endows 10 scholarships for its II School of Economics on Social Challenges: Aging, Gender, and Immigration at ...</a></h3>
<a class="link-primary" href="all_news_blog_detail.asp?id=523">See more</a>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<!-- Bloque Últimas Publicaciones -->
<section id="blq-last-pubs">

In [14]:
# Based on the output of `soup.findall()`, proceed to Step 3
# Step 3: Locate the navigation menu
nav_items = soup.find('ul', id='cemfi-menu-top').find_all('li', class_='nav-item')

# Step 4: Extract the text and links
nav_links = []
for item in nav_items:
    section = item.find('a').get_text(strip=True)
    link = item.find('a')['href']
    nav_links.append({'Section': section, 'Link': link})

    
# Load pandas
import pandas as pd
    
# Step 5: Convert the list of dictionaries to a DataFrame
df_nav_links = pd.DataFrame(nav_links)

df_nav_links

    Section                 Link
0  Research  /research/index.asp
1  Programs  /programs/index.asp
2    People    /people/index.asp
3     About     /about/index.asp


### Next, try the same exercise with the CREI webpage

In [16]:
import requests
from bs4 import BeautifulSoup

# Step 1: Send a GET request to the webpage
url = "https://crei.cat/"
response = requests.get(url)

# Step 2: Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

print(soup.find_all())

[<html lang="en-US">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<link href="https://gmpg.org/xfn/11" rel="profile"/>
<title>CREI – Centre de Recerca en Economia Internacional</title>
<link href="https://crei.cat/wp-content/themes/crei-theme/favicon.png" rel="icon" sizes="64x64" type="image/png"/>
<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-22729428-1', 'auto');
		ga('send', 'pageview');

	</script>
<meta content="max-image-preview:large" name="robots"/>
<style>img:is([sizes="auto" i], [sizes^="auto," i]) { contain-intrinsic-size: 3000px 1500px }</style>
<script type="text/javascript">
/* <![CDATA[ */
window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/15.1.0\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/15.1.0\/svg\/","svgExt":".svg","source":{"concatemoji":"https:\/\/crei.cat\/wp-includes\/js\/wp-emoji-release.min.js?ver=841920b67394c403ae3ed45dbd7d1b72"}};
/*! This file is auto-generated */
!function(i,n){var o,s,e;function c(e){try{var t={supportTests:e,timestamp:(new Date).valueOf()};sessionStorage.setItem(o,JSON.stringify(t))}catch(e){}}function p(e,t,n){e.clearRect(0,0,e.canvas.width,e.canvas.height),e.fillText(t,0,0);var t=new Uint32Array(e.getImageData(0,0,e.canvas.width,e.canvas.height).data),r=(e.clearRect(0,0,e.canvas.width,e.canvas.height),e.fillText(n,0,0),new Uint32Array(e.getImageData(0,0,e.canvas.width,e.canvas.height).data));return t.every(function(e,t){return e===r[t]})}function u(e,t,n){switch(t){case"flag":return n(e,"\ud83c\udff3\ufe0f\u200d\u26a7\ufe0f","\ud83c\udff3\ufe0f\u200b\u26a7\ufe0f")?!1:!n(e,"\ud83c\uddfa\ud83c\uddf3","\ud83c\uddfa\u200b\ud83c\uddf3")&&!n(e,"\ud83c\udff4\udb40\udc67\udb40\udc62\udb40\udc65\udb40\udc6e\udb40\udc67\udb40\udc7f","\ud83c\udff4\u200b\udb40\udc67\u200b\udb40\udc62\u200b\udb40\udc65\u200b\udb40\udc6e\u200b\udb40\udc67\u200b\udb40\udc7f");case"emoji":return!n(e,"\ud83d\udc26\u200d\ud83d\udd25","\ud83d\udc26\u200b\ud83d\udd25")}return!1}function f(e,t,n){var r="undefined"!=typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope?new OffscreenCanvas(300,150):i.createElement("canvas"),a=r.getContext("2d",{willReadFrequently:!0}),o=(a.textBaseline="top",a.font="600 32px Arial",{});return e.forEach(function(e){o[e]=t(a,e,n)}),o}function t(e){var t=i.createElement("script");t.src=e,t.defer=!0,i.head.appendChild(t)}"undefined"!=typeof Promise&&(o="wpEmojiSettingsSupports",s=["flag","emoji"],n.supports={everything:!0,everythingExceptFlag:!0},e=new Promise(function(e){i.addEventListener("DOMContentLoaded",e,{once:!0})}),new Promise(function(t){var n=function(){try{var e=JSON.parse(sessionStorage.getItem(o));if("object"==typeof e&&"number"==typeof e.timestamp&&(new Date).valueOf()<e.timestamp+604800&&"object"==typeof e.supportTests)return e.supportTests}catch(e){}return null}();if(!n){if("undefined"!=typeof Worker&&"undefined"!=typeof OffscreenCanvas&&"undefined"!=typeof URL&&URL.createObjectURL&&"undefined"!=typeof Blob)try{var e="postMessage("+f.toString()+"("+[JSON.stringify(s),u.toString(),p.toString()].join(",")+"));",r=new Blob([e],{type:"text/javascript"}),a=new Worker(URL.createObjectURL(r),{name:"wpTestEmojiSupports"});return void(a.onmessage=function(e){c(n=e.data),a.terminate(),t(n)})}catch(e){}c(n=f(s,u,p))}t(n)}).then(function(e){for(var t in e)n.supports[t]=e[t],n.supports.everything=n.supports.everything&&n.supports[t],"flag"!==t&&(n.supports.everythingExceptFlag=n.supports.everythingExceptFlag&&n.supports[t]);n.supports.everythingExceptFlag=n.supports.everythingExceptFlag&&!n.supports.flag,n.DOMReady=!1,n.readyCallback=function(){n.DOMReady=!0}}).then(function(){return e}).then(function(){var e;n.supports.everything||(n.readyCallback(),(e=n.source||{}).concatemoji?t(e.concatemoji):e.wpemoji&&e.twemoji&&(t(e.twemoji),t(e.wpemoji)))}))}((window,document),window._wpemojiSettings);
/* ]]> */
</script>
<style id="wp-emoji-styles-inline-css" type="text/css">

	img.wp-smiley, img.emoji {
		display: inline !important;
		border: none !important;
		box-shadow: none !important;
		height: 1em !important;
		width: 1em !important;
		margin: 0 0.07em !important;
		vertical-align: -0.1em !important;
		background: none !important;
		padding: 0 !important;
	}
</style>
<link href="https://crei.cat/wp-includes/css/dist/block-library/style.min.css?ver=841920b67394c403ae3ed45dbd7d1b72" id="wp-block-library-css" media="all" rel="stylesheet" type="text/css">
<style id="classic-theme-styles-inline-css" type="text/css">
/*! This file is auto-generated */
.wp-block-button__link{color:#fff;background-color:#32373c;border-radius:9999px;box-shadow:none;text-decoration:none;padding:calc(.667em + 2px) calc(1.333em + 2px);font-size:1.125em}.wp-block-file__button{background:#32373c;color:#fff;text-decoration:none}
</style>
<style id="global-styles-inline-css" type="text/css">
:root{--wp--preset--aspect-ratio--square: 1;--wp--preset--aspect-ratio--4-3: 4/3;--wp--preset--aspect-ratio--3-4: 3/4;--wp--preset--aspect-ratio--3-2: 3/2;--wp--preset--aspect-ratio--2-3: 2/3;--wp--preset--aspect-ratio--16-9: 16/9;--wp--preset--aspect-ratio--9-16: 9/16;--wp--preset--color--black: #000000;--wp--preset--color--cyan-bluish-gray: #abb8c3;--wp--preset--color--white: #ffffff;--wp--preset--color--pale-pink: #f78da7;--wp--preset--color--vivid-red: #cf2e2e;--wp--preset--color--luminous-vivid-orange: #ff6900;--wp--preset--color--luminous-vivid-amber: #fcb900;--wp--preset--color--light-green-cyan: #7bdcb5;--wp--preset--color--vivid-green-cyan: #00d084;--wp--preset--color--pale-cyan-blue: #8ed1fc;--wp--preset--color--vivid-cyan-blue: #0693e3;--wp--preset--color--vivid-purple: #9b51e0;--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple: linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%);--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan: linear-gradient(135deg,rgb(122,220,180) 0%,rgb(0,208,130) 100%);--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange: linear-gradient(135deg,rgba(252,185,0,1) 0%,rgba(255,105,0,1) 100%);--wp--preset--gradient--luminous-vivid-orange-to-vivid-red: linear-gradient(135deg,rgba(255,105,0,1) 0%,rgb(207,46,46) 100%);--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray: linear-gradient(135deg,rgb(238,238,238) 0%,rgb(169,184,195) 100%);--wp--preset--gradient--cool-to-warm-spectrum: linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%);--wp--preset--gradient--blush-light-purple: linear-gradient(135deg,rgb(255,206,236) 0%,rgb(152,150,240) 100%);--wp--preset--gradient--blush-bordeaux: linear-gradient(135deg,rgb(254,205,165) 0%,rgb(254,45,45) 50%,rgb(107,0,62) 100%);--wp--preset--gradient--luminous-dusk: linear-gradient(135deg,rgb(255,203,112) 0%,rgb(199,81,192) 50%,rgb(65,88,208) 100%);--wp--preset--gradient--pale-ocean: linear-gradient(135deg,rgb(255,245,203) 0%,rgb(182,227,212) 50%,rgb(51,167,181) 100%);--wp--preset--gradient--electric-grass: linear-gradient(135deg,rgb(202,248,128) 0%,rgb(113,206,126) 100%);--wp--preset--gradient--midnight: linear-gradient(135deg,rgb(2,3,129) 0%,rgb(40,116,252) 100%);--wp--preset--font-size--small: 13px;--wp--preset--font-size--medium: 20px;--wp--preset--font-size--large: 36px;--wp--preset--font-size--x-large: 42px;--wp--preset--spacing--20: 0.44rem;--wp--preset--spacing--30: 0.67rem;--wp--preset--spacing--40: 1rem;--wp--preset--spacing--50: 1.5rem;--wp--preset--spacing--60: 2.25rem;--wp--preset--spacing--70: 3.38rem;--wp--preset--spacing--80: 5.06rem;--wp--preset--shadow--natural: 6px 6px 9px rgba(0, 0, 0, 0.2);--wp--preset--shadow--deep: 12px 12px 50px rgba(0, 0, 0, 0.4);--wp--preset--shadow--sharp: 6px 6px 0px rgba(0, 0, 0, 0.2);--wp--preset--shadow--outlined: 6px 6px 0px -3px rgba(255, 255, 255, 1), 6px 6px rgba(0, 0, 0, 1);--wp--preset--shadow--crisp: 6px 6px 0px rgba(0, 0, 0, 1);}:where(.is-layout-flex){gap: 0.5em;}:where(.is-layout-grid){gap: 0.5em;}body .is-layout-flex{display: flex;}.is-layout-flex{flex-wrap: wrap;align-items: center;}.is-layout-flex > :is(*, div){margin: 0;}body .is-layout-grid{display: grid;}.is-layout-grid > :is(*, div){margin: 0;}:where(.wp-block-columns.is-layout-flex){gap: 2em;}:where(.wp-block-columns.is-layout-grid){gap: 2em;}:where(.wp-block-post-template.is-layout-flex){gap: 1.25em;}:where(.wp-block-post-template.is-layout-grid){gap: 1.25em;}.has-black-color{color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-color{color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-color{color: var(--wp--preset--color--white) !important;}.has-pale-pink-color{color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-color{color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-color{color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-color{color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-color{color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-color{color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-color{color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-color{color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-color{color: var(--wp--preset--color--vivid-purple) !important;}.has-black-background-color{background-color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-background-color{background-color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-background-color{background-color: var(--wp--preset--color--white) !important;}.has-pale-pink-background-color{background-color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-background-color{background-color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-background-color{background-color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-background-color{background-color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-background-color{background-color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-background-color{background-color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-background-color{background-color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-background-color{background-color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-background-color{background-color: var(--wp--preset--color--vivid-purple) !important;}.has-black-border-color{border-color: var(--wp--preset--color--black) !important;}.has-cyan-bluish-gray-border-color{border-color: var(--wp--preset--color--cyan-bluish-gray) !important;}.has-white-border-color{border-color: var(--wp--preset--color--white) !important;}.has-pale-pink-border-color{border-color: var(--wp--preset--color--pale-pink) !important;}.has-vivid-red-border-color{border-color: var(--wp--preset--color--vivid-red) !important;}.has-luminous-vivid-orange-border-color{border-color: var(--wp--preset--color--luminous-vivid-orange) !important;}.has-luminous-vivid-amber-border-color{border-color: var(--wp--preset--color--luminous-vivid-amber) !important;}.has-light-green-cyan-border-color{border-color: var(--wp--preset--color--light-green-cyan) !important;}.has-vivid-green-cyan-border-color{border-color: var(--wp--preset--color--vivid-green-cyan) !important;}.has-pale-cyan-blue-border-color{border-color: var(--wp--preset--color--pale-cyan-blue) !important;}.has-vivid-cyan-blue-border-color{border-color: var(--wp--preset--color--vivid-cyan-blue) !important;}.has-vivid-purple-border-color{border-color: var(--wp--preset--color--vivid-purple) !important;}.has-vivid-cyan-blue-to-vivid-purple-gradient-background{background: var(--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple) !important;}.has-light-green-cyan-to-vivid-green-cyan-gradient-background{background: var(--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan) !important;}.has-luminous-vivid-amber-to-luminous-vivid-orange-gradient-background{background: var(--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange) !important;}.has-luminous-vivid-orange-to-vivid-red-gradient-background{background: var(--wp--preset--gradient--luminous-vivid-orange-to-vivid-red) !important;}.has-very-light-gray-to-cyan-bluish-gray-gradient-background{background: var(--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray) !important;}.has-cool-to-warm-spectrum-gradient-background{background: var(--wp--preset--gradient--cool-to-warm-spectrum) !important;}.has-blush-light-purple-gradient-background{background: var(--wp--preset--gradient--blush-light-purple) !important;}.has-blush-bordeaux-gradient-background{background: var(--wp--preset--gradient--blush-bordeaux) !important;}.has-luminous-dusk-gradient-background{background: var(--wp--preset--gradient--luminous-dusk) !important;}.has-pale-ocean-gradient-background{background: var(--wp--preset--gradient--pale-ocean) !important;}.has-electric-grass-gradient-background{background: var(--wp--preset--gradient--electric-grass) !important;}.has-midnight-gradient-background{background: var(--wp--preset--gradient--midnight) !important;}.has-small-font-size{font-size: var(--wp--preset--font-size--small) !important;}.has-medium-font-size{font-size: var(--wp--preset--font-size--medium) !important;}.has-large-font-size{font-size: var(--wp--preset--font-size--large) !important;}.has-x-large-font-size{font-size: var(--wp--preset--font-size--x-large) !important;}
:where(.wp-block-post-template.is-layout-flex){gap: 1.25em;}:where(.wp-block-post-template.is-layout-grid){gap: 1.25em;}
:where(.wp-block-columns.is-layout-flex){gap: 2em;}:where(.wp-block-columns.is-layout-grid){gap: 2em;}
:root :where(.wp-block-pullquote){font-size: 1.5em;line-height: 1.6;}
</style>
<link href="https://crei.cat/wp-content/plugins/cookie-law-info/legacy/public/css/cookie-law-info-public.css?ver=3.2.10" id="cookie-law-info-css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://crei.cat/wp-content/plugins/cookie-law-info/legacy/public/css/cookie-law-info-gdpr.css?ver=3.2.10" id="cookie-law-info-gdpr-css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://crei.cat/wp-content/themes/crei-theme/assets/css/styles.css" id="mg-style-css" media="all" rel="stylesheet" type="text/css"/>
<style id="akismet-widget-style-inline-css" type="text/css">

			.a-stats {
				--akismet-color-mid-green: #357b49;
				--akismet-color-white: #fff;
				--akismet-color-light-grey: #f6f7f7;

				max-width: 350px;
				width: auto;
			}

			.a-stats * {
				all: unset;
				box-sizing: border-box;
			}

			.a-stats strong {
				font-weight: 600;
			}

			.a-stats a.a-stats__link,
			.a-stats a.a-stats__link:visited,
			.a-stats a.a-stats__link:active {
				background: var(--akismet-color-mid-green);
				border: none;
				box-shadow: none;
				border-radius: 8px;
				color: var(--akismet-color-white);
				cursor: pointer;
				display: block;
				font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen-Sans', 'Ubuntu', 'Cantarell', 'Helvetica Neue', sans-serif;
				font-weight: 500;
				padding: 12px;
				text-align: center;
				text-decoration: none;
				transition: all 0.2s ease;
			}

			/* Extra specificity to deal with TwentyTwentyOne focus style */
			.widget .a-stats a.a-stats__link:focus {
				background: var(--akismet-color-mid-green);
				color: var(--akismet-color-white);
				text-decoration: none;
			}

			.a-stats a.a-stats__link:hover {
				filter: brightness(110%);
				box-shadow: 0 4px 12px rgba(0, 0, 0, 0.06), 0 0 2px rgba(0, 0, 0, 0.16);
			}

			.a-stats .count {
				color: var(--akismet-color-white);
				display: block;
				font-size: 1.5em;
				line-height: 1.4;
				padding: 0 13px;
				white-space: nowrap;
			}

</style>
<script id="jquery-core-js" src="https://crei.cat/wp-includes/js/jquery/jquery.min.js?ver=3.7.1" type="text/javascript"></script>
<script id="jquery-migrate-js" src="https://crei.cat/wp-includes/js/jquery/jquery-migrate.min.js?ver=3.4.1" type="text/javascript"></script>
<script id="cookie-law-info-js-extra" type="text/javascript">
/* <![CDATA[ */
var Cli_Data = {"nn_cookie_ids":["test_cookie","li_sugr","bcookie","bscookie","_ga","_gid","_hjFirstSeen","_hjSessionUser_*","_hjSession_*","AnalyticsSyncHistory","lidc","_hjAbsoluteSessionInProgress","UserMatchHistory","li_gc","_gat","AWSALB","dbpb5zDmgTrLAA1Q6g@@","_hjIncludedInSessionSample_3062403","CookieLawInfoConsent","cookielawinfo-checkbox-necessary","cookielawinfo-checkbox-non-necessary","cookielawinfo-checkbox-functional","cookielawinfo-checkbox-performance","cookielawinfo-checkbox-analytics","cookielawinfo-checkbox-advertisement","cookielawinfo-checkbox-others","AWSALBCORS"],"cookielist":[],"non_necessary_cookies":{"necessary":["CookieLawInfoConsent","AWSALBCORS"],"functional":["lidc","_hjAbsoluteSessionInProgress","UserMatchHistory","li_gc"],"performance":["_gat","AWSALB"],"analytics":["_ga","_gid","_hjFirstSeen","_hjSessionUser_*","_hjSession_*","AnalyticsSyncHistory"],"advertisement":["test_cookie","li_sugr","bcookie","bscookie"],"others":["dbpb5zDmgTrLAA1Q6g@@","_hjIncludedInSessionSample_3062403"]},"ccpaEnabled":"","ccpaRegionBased":"","ccpaBarEnabled":"","strictlyEnabled":["necessary","obligatoire"],"ccpaType":"gdpr","js_blocking":"1","custom_integration":"","triggerDomRefresh":"","secure_cookies":""};
var cli_cookiebar_settings = {"animate_speed_hide":"500","animate_speed_show":"500","background":"#FFF","border":"#b1a6a6c2","border_on":"","button_1_button_colour":"#61a229","button_1_button_hover":"#4e8221","button_1_link_colour":"#fff","button_1_as_button":"1","button_1_new_win":"","button_2_button_colour":"#333","button_2_button_hover":"#292929","button_2_link_colour":"#444","button_2_as_button":"","button_2_hidebar":"","button_3_button_colour":"#3566bb","button_3_button_hover":"#2a5296","button_3_link_colour":"#fff","button_3_as_button":"1","button_3_new_win":"","button_4_button_colour":"#000","button_4_button_hover":"#000000","button_4_link_colour":"#333333","button_4_as_button":"","button_7_button_colour":"#61a229","button_7_button_hover":"#4e8221","button_7_link_colour":"#fff","button_7_as_button":"1","button_7_new_win":"","font_family":"inherit","header_fix":"","notify_animate_hide":"1","notify_animate_show":"","notify_div_id":"#cookie-law-info-bar","notify_position_horizontal":"right","notify_position_vertical":"bottom","scroll_close":"","scroll_close_reload":"","accept_close_reload":"","reject_close_reload":"","showagain_tab":"1","showagain_background":"#fff","showagain_border":"#000","showagain_div_id":"#cookie-law-info-again","showagain_x_position":"100px","text":"#333333","show_once_yn":"","show_once":"10000","logging_on":"","as_popup":"","popup_overlay":"1","bar_heading_text":"","cookie_bar_as":"banner","popup_showagain_position":"bottom-right","widget_position":"left"};
var log_object = {"ajax_url":"https:\/\/crei.cat\/wp-admin\/admin-ajax.php"};
/* ]]> */
</script>
<script id="cookie-law-info-js" src="https://crei.cat/wp-content/plugins/cookie-law-info/legacy/public/js/cookie-law-info-public.js?ver=3.2.10" type="text/javascript"></script>
<script id="mg-scripts-js" src="https://crei.cat/wp-content/themes/crei-theme/assets/js/all.min.js" type="text/javascript"></script>

In [17]:
# Based on the output of `soup.findall()`, proceed to Step 3 (locate <div class> <ul class> <li class>)
# Step 3: Locate the navigation menu
nav_items = soup.find('ul', id='menu-header-menu').find_all('li', class_='menu-item')

# Step 4: Extract the text and links
nav_links = []
for item in nav_items:
    section = item.find('a').get_text(strip=True)
    link = item.find('a')['href']
    nav_links.append({'Section': section, 'Link': link})

# Step 5: Convert the list of dictionaries to a DataFrame
df_nav_links = pd.DataFrame(nav_links)

df_nav_links

          Section                              Link
0            Home                                 /
1      About CREI      https://crei.cat/about-crei/
2          People          https://crei.cat/people/
3  Working Papers  https://crei.cat/working-papers/
4        Opuscles        https://crei.cat/opuscles/
5      Activities      https://crei.cat/activities/
6            News            https://crei.cat/news/
7    Job Openings    https://crei.cat/work-with-us/
8         Contact         https://crei.cat/contact/
9           Links           https://crei.cat/links/

### We can also scrape the recent publications

In [19]:
import requests
from bs4 import BeautifulSoup

# Step 1: Send a GET request to the webpage
url = "https://crei.cat/"
response = requests.get(url)

# Step 2: Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

# Step 3: Locate the recent publications carousel
pub_items = soup.find('section', id='last-papers').find_all('article', class_='publication publications-section')
#print(pub_items)

# Step 4: Extract paper details
recent_pubs = []
for pubs in pub_items:
    title  = pubs.find('h3', class_='crei-post-title publications-title').get_text(strip=True)
    journal  = pubs.find('h5', class_='publication-date').get_text(strip=True)
    
    # Extract all authors (assuming authors are listed inside a span or similar tag)
        # a.text.strip() retrieves the text inside each <a> tag and removes any leading or trailing whitespace.
        # for a in pubs.find_all('a'): Iterates over all <a> tags found within the pub_item object
        # if a.text.strip(): Filters out any entries that are empty after stripping whitespace
    authors = [a.text.strip() for a in pubs.find_all('a') if a.text.strip()]
    other_author = [span.text.strip() for span in pubs.find_all('span') if span.text.strip()]
    
    # Combine CREI-affiliated authors w/ non-affiliated coauthors into one list
    authors.extend(other_author)
    
    recent_pubs.append({'Authors': ', '.join(authors), 'Title': title, 'Journal': journal})

    
# Display the scraped events
df_pubs = pd.DataFrame(recent_pubs)

df_pubs

,Authors,Title,Journal
0,"Fornaro, L., F. Romei","""An International Perspective on Inflation dur...",Forthcoming in 2025
1,"Ponzetto, G., U. Troiano","""Social Capital, Government Expenditures, and ...","Journal of the European Economic Association, ..."
2,"Broner, F., A. Martin, C. Trebesch, J. Meyer, ...","""Hegemony and International Alignment""",American Economic Association: Papers & Procee...
3,"R. Marimon, A. Abraham, E. Cárceles, Y. Liu","""On the Optimal Design of a Financial Stabilit...","Forthcoming inThe Review of Economic Studies, ..."
4,"L. Fornaro, G. Benigno, M. Wolf","""The Global Financial Resource Curse""","American Economic Review, 2024, 115 (1), 220-262"
5,"H. Reichardt, L. Althoff","""Jim Crow and Black Economic Progress After Sl...","Quarterly Journal of Economics, 2024, 139 (4),..."
6,"Galí, J., D. Debortoli","""Idiosyncratic Income Risk and Aggregate Fluct...","American Economic Journal: Macroeconomics, 202..."
7,"Nagy, D., C. Ducruet, R. Juhász, C. Steinwender","""All Aboard: The Effects of Port Development""","Journal of International Economics, 2024, Volu..."
8,"Asriyan, V., A. Martin, V. Vanasco, L. Laeven,...","""Falling Interest Rates and Credit Reallocatio...","Forthcoming inThe Review of Economic Studies, ..."
9,"Baley, I., Lars Ljungqvist, Thomas J. Sargent","""Returns to labour mobility""","The Economic Journal, 2024, 135, 430–454"

### We can scrape the seminar list next

In [22]:
import requests
from bs4 import BeautifulSoup, NavigableString, Tag

# Step 1: Send a GET request to the webpage
url = "https://crei.cat/seminars/crei-upf-seminar/"
response = requests.get(url)

# Step 2: Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')
#print(soup.find_all())

# Step 3: Locate the recent publications carousel
seminar_items = soup.find('section', id='page').find_all('article', class_='post crei-event')
#print(seminar_items)


# Step 4: Extract seminar details
# Need to deal with <br> and how to separate author from title
seminars = []
for sems in seminar_items:
    author = sems.find('h5', class_='crei-event-speaker').find_all('p')[0].get_text(strip=True)
    #title  = sems.find('h5', class_='crei-event-speaker').find('p').decode_contents().split('<br/>')
    date   = sems.find('h3', id='crei-event-date').get_text(strip=True)
    seminars.append({'Date': date, 'Author': author})
        
# Display the scraped events
df_seminars = pd.DataFrame(seminars)

df_seminars

                  Date                                             Author
0   September 16, 2024  Agostina Brinatti (Yale University)“Third-Coun...
1   September 30, 2024  Sebastian Graves (University of Cambridge)“The...
2      October 7, 2024  Karthik Sastry (Princeton University)“A Theory...
3     October 14, 2024  Ilse Lindenlaub (Yale University)“Meritocracy ...
4     October 21, 2024  Hugo Lhuillier (University of Chicago)“Should ...
5     November 4, 2024  Olivia Bordeu (Princeton University)“Commuting...
6    November 11, 2024  Joel Flynn (Yale University)“Quick-Fixing: Nea...
7    November 18, 2024  Felipe Saffie (University of Virginia)“Non-Con...
8     December 2, 2024  Tatjana Kleineberg (The World Bank)“Gender Bar...
9    February 24, 2025  Nitya Pandalai-Nayar (University of Texas, Aus...
10       March 6, 2025  -Thursday-Tim Kehoe (University of Minnesota)“...
11      March 10, 2025  Federico Huneeus (Duke University)“Production ...
12      March 17, 2025  Juan Carlos Suárez Serrato (Stanford GSB)“The ...
13      March 24, 2025  Paolo Martellini (NYU Stern)“Capital Reallocat...
14      March 31, 2025  Cristina Arellano (Minneapolis Fed)“Official S...
15       April 7, 2025  -ONLINE-David Baqaee (UCLA)“Consumer Surplus f...
16      April 28, 2025  Alp Simsek (Yale University)“Financial Conditi...
17         May 5, 2025  Job Boerma (UW Madison)”Composite Sorting”(wit...
18        May 12, 2025  Olivier Coibion (University of Texas, Austin)“...
19        May 19, 2025  Chen Lian (UC, Berkeley)“Why Do Workers Dislik...
20        May 26, 2025  Alireza Tahbaz-Salehi (Kellogg, Northwestern U...

### Scrape the Academic Planning of their Master

In [24]:
# Import necessary libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Step 1: Send a GET request to the webpage
url = "https://www.cemfi.es/programs/master/course_description.asp"
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    print("Successfully accessed the webpage!")
else:
    print("Failed to access the webpage.")

# Step 2: Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')
# print(soup.find_all())

# Step 3: Find all divs that contain the tables
table_divs = soup.find_all('div', class_='table table-responsive p-3 tbl-4 mt-5 mb-0')

# Initialize lists to hold the extracted data
modules = []
courses = []
professors = []

# Step 4: Loop through each table div and extract the data
for table_div in table_divs:
    # Extract the module name from the <th> tag in the <thead>
    module_name = table_div.find('th').get_text(strip=True)

    # Find the table and then loop through each row in the table body
    table = table_div.find('table', class_='w-100')
    for row in table.find('tbody').find_all('tr')[1:]:  # Skipping the header row (th) "Course" "Professor" 
        columns = row.find_all('td')
        course_name = columns[0].get_text(strip=True)
        professor_name = columns[1].get_text(strip=True)

        # Append the extracted data to the lists
        modules.append(module_name)
        courses.append(course_name)
        professors.append(professor_name)
   
# Step 5: Create a DataFrame from the extracted data
df_courses = pd.DataFrame({
    'Module': modules,
    'Course': courses,
    'Professor': professors
})

# Display the scraped events
df_courses

Successfully accessed the webpage!

,Module,Course,Professor
0,Preliminary Module,Mathematics,Dante Amengual
1,Module I: Core courses / Term 1,Microeconomics,Guillermo Caruana
2,Module I: Core courses / Term 1,Macroeconomics I,Josep Pijoan-Mas
3,Module I: Core courses / Term 1,Statistical Methods in Econometrics,Pedro Mira
4,Module I: Core courses / Term 2,Uncertainty and Information,Guillermo Caruana
5,Module I: Core courses / Term 2,Econometrics,Manuel Arellano
6,Module I: Core courses / Term 2,Macroeconomics II,Kurt Mitman
7,Module II: Elective courses / Term 3,Markets and Organizations,Gerard Llobet
8,Module II: Elective courses / Term 3,Quantitative Macroeconomics,Federico Kochen
9,Module II: Elective courses / Term 3,Financial Economics,Rafael Repullo
10,Module II: Elective courses / Term 3,Corporate Finance,Nicolas Serrano-Velarde
11,Module II: Elective courses / Term 3,Applied Macroeconometrics,"Florens Odendahl,Galo Nuño"
12,Module II: Elective courses / Term 3,Applied Microeconometrics,"Manuel Arellano,Manuel Bagues"
13,Module II: Elective courses / Term 4,Microeconometrics,Dmitry Arkhangelsky
14,Module II: Elective courses / Term 4,Regulation and Competition Policy,Gerard Llobet
15,Module II: Elective courses / Term 4,Economics of Banking,David Martínez-Miera
16,Module II: Elective courses / Term 4,Labor Economics,Tom Zohar
17,Module II: Elective courses / Term 4,Topics in Macroeconomics,Nezih Guner
18,Module II: Elective courses / Term 4,Urban Economics,Diego Puga
19,Module II: Elective courses / Term 5,Data Science for Economics,Christopher Rauh
20,Module II: Elective courses / Term 5,Time Series Econometrics,Enrique Sentana
21,Module II: Elective courses / Term 5,Topics in Applied Microeconomics,"Samuel Bentolila,Agustín Casas"
22,Module II: Elective courses / Term 5,Topics in Finance,"Enrique Sentana,Andrea Sy"
23,Module II: Elective courses / Term 5,International Macroeconomics,Sebastián Fanelli
24,Module II: Elective courses / Term 5,Empirical Industrial Organization,Susanna Esteban
25,Module III: Introduction to research / Term 2-6,Applied Economics Workshop,Samuel Bentolila
26,Module III: Introduction to research / Term 2-6,Research Workshop,"Diego Puga,Nezih Guner,Manuel Arellano"
27,Module III: Introduction to research / Term 2-6,Master Thesis,Manuel Arellano

### Get CREI Faculty Profiles

In [26]:
# Import necessary libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Step 1: Send a GET request to the webpage
url = "https://crei.cat/people/"
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    print("Successfully accessed the webpage!")
else:
    print("Failed to access the webpage.")

# Step 2: Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')
# print(soup.find_all())

# Step 3: Find all the faculty member entries
faculty_main = soup.find('article', id="researchers").find_all('div', class_="people-detail researcher")
faculty_assoc = soup.find('article', id="a-researchers").find_all('div', class_="people-detail a-researcher")


# Step 4: Iterate over each faculty member entry to extract information
faculty_main_data = []
faculty_assoc_data = []


for faculty in faculty_main:
    # Extract name
    name = faculty.find('a').get_text(strip=True)

#     # Extract profile link
#     profile_link = faculty.find('a')['href']

    # Extract degree and institution
    degree_institution = faculty.find('div', class_="user-data user-phd").get_text(strip=True)

    # Extract position
    position = faculty.find('div', class_="user-data user-office").get_text(strip=True)

    # Extract fields of research
    fields = faculty.find('ul', class_="user-interests-list").get_text(strip=True)
    
     # Append the extracted data to the list
    faculty_main_data.append({
        'Name': name,
#         'Profile Link': profile_link,
        'Degree and Institution': degree_institution,
        'Position': position,
        'Fields': fields
    })

    
for faculty in faculty_assoc:
    # Extract name
    name = faculty.find('a').get_text(strip=True)

   # Extract degree and institution
    degree_institution = faculty.find('div', class_="user-data user-phd").get_text(strip=True)

    # Extract position
    position = faculty.find('div', class_="user-data user-office").get_text(strip=True)

    # Extract fields of research
    fields = faculty.find('ul', class_="user-interests-list").get_text(strip=True)
    
     # Append the extracted data to the list
    faculty_assoc_data.append({
        'Name': name,
        'Degree and Institution': degree_institution,
        'Position': position,
        'Fields': fields
    })    
    
    
# Convert the list of dictionaries to a pandas DataFrame
df_faculty1 = pd.DataFrame(faculty_main_data)
df_faculty2 = pd.DataFrame(faculty_assoc_data)

# APPEND two DataFrames (and reset indexing)
df_full = pd.concat([df_faculty1, df_faculty2]).reset_index(drop=True)

df_full

Successfully accessed the webpage!

,Name,Degree and Institution,Position,Fields
0,Vladimir Asriyan,"PhD: University of California, Berkeley","(CREI Senior Researcher, UPF Adjunct Professor...","Finance, Information Economics and Macroeconomics"
1,Fernando Broner,PhD: MIT,"(CREI Senior Researcher, UPF Adjunct Professor...",Macroeconomics and International Economics
2,Luca Fornaro,PhD: LSE,"(CREI Senior Researcher, UPF Adjunct Professor...",International Economics and Monetary Economics
3,Jordi Galí,PhD: MIT,"(CREI Senior Researcher, UPF Professor and Bar...",Macroeconomic Theory and Monetary Economics
4,Mishel Ghassibe,PhD: University of Oxford,(CREI Junior Researcher),"Macroeconomics, Production Networks, Monetary ..."
5,Elisa Giannone,PhD: University of Chicago,"(CREI Junior Researcher, Barcelona School of E...","Devopment Economics, Economic Growth, Internat..."
6,Albert Marcet,PhD: University of Minnesota,"(ICREA Research Professor at CREI, Barcelona S...","Financial Economics, Econometrics, Information..."
7,Alberto Martin,PhD: Columbia University,"(CREI Senior Researcher, UPF Adjunct Professor...","Financial Markets, International Economics and..."
8,Dávid Krisztián Nagy,PhD: Princeton,"(CREI Senior Researcher, UPF Adjunct Professor...","Economic Geography and International Trade,"
9,Giacomo Ponzetto,PhD: Harvard,"(CREI Senior Researcher, UPF Adjunct Professor...","Applied Micro, Financial Economics, Internatio..."
10,Hugo Reichardt,PhD: LSE,(CREI Junior Researcher),"Macroeconomics, Economic History"
11,Edouard Schaal,PhD: Princeton,"(ICREA Research Professor at CREI, UPF Adjunct...","Business cycle, Information frictions, Labor M..."
12,Victoria Vanasco,PhD: University of California Berkeley,"(CREI Senior Researcher, UPF Adjunct Professor...","Corporate Finance, Games with Asymmetric Infor..."
13,Jaume Ventura,PhD: Harvard University,"(CREI Director and Senior Researcher, UPF Prof...",International Economics and Macroeconomics
14,Isaac Baley,PhD: NYU,"(CREI Associate Researcher, UPF Assistant Prof...","Information, International, Labor, Macroeconomics"
15,Andrea Caggese,PhD: London School of Economics,"(CREI Associate Researcher, UPF Associate Prof...","Applied and Quantitative Macroeconomics, Busin..."
16,Davide Debortoli,PhD: Universitat Pompeu Fabra,"(CREI Associate Researcher, ICREA Research Pro...","Fiscal Policy, Macroeconomics and Monetary Policy"
17,Jan Eeckhout,PhD: London School of Economics,"(CREI Associate Researcher, ICREA Research Pro...","Labor Markets, Market Power and Urban Economics"
18,Teresa Garcia-Milà,PhD: University of Minnesota,"(CREI Associate Researcher, UPF Professor and ...","Macroeconomics, Applied Microeconomics and, Ec..."
19,Manuel García-Santana,PhD: CEMFI,"(CREI Associate Researcher, UPF Associate Prof...","Macroeconomics and, Trade, Growth and Development"
20,Priit Jeenas,PhD: New York University,"(CREI Associate Researcher, Assistant Professo...","Macroeconomics, Monetary Economics and Financi..."
21,Ramon Marimon,PhD: Northwestern University,"(CREI Associate Researcher, Professor Emeritus...","Macroeconomics, Debt & Monetary Theory, Learni..."
22,Geert Mesters,PhD: Vrije University Amsterdam,"(CREI Associate Researcher, UPF Associate Prof...","Applied Macroeconomics, Econometrics and Stati..."
23,Martí Mestieri\t\t\t\t\t\t (on leave),PhD: MIT,(CREI Associate Researcher and UPF Professor),"Economic Growth, International Trade, and Macr..."
24,Joan Monràs,PhD: Columbia University,"(CREI Associate Researcher, Associate Professo...","International Economics, Labor Economics, and ..."
25,Barbara Rossi\t\t\t\t\t\t (on leave),PhD: Princeton University,"(CREI Associate Researcher, ICREA Professor at...","International Economics, Macroeconomics and Ec..."